import { describe, it, expect } from 'vitest'
import { stripImageMetadata, detectImageFormat } from '../electron/services/imageMetadata'

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])

function crc32(buf: Buffer): number {
  let c: number
  const table: number[] = []
  for (let n = 0; n < 256; n++) {
    c = n
    for (let k = 0; k < 8; k++) c = c & 1 ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1)
    table[n] = c
  }
  let crc = 0xFFFFFFFF
  for (let i = 0; i < buf.length; i++) crc = table[(crc ^ buf[i]) & 0xFF] ^ (crc >>> 8)
  return (crc ^ 0xFFFFFFFF) >>> 0
}

function pngChunk(type: string, data: string): Buffer {
  const typeBuf = Buffer.from(type, 'ascii')
  const dataBuf = Buffer.from(data, 'latin1')
  const lenBuf = Buffer.alloc(4); lenBuf.writeUInt32BE(dataBuf.length)
  const crcBuf = Buffer.alloc(4); crcBuf.writeUInt32BE(crc32(Buffer.concat([typeBuf, dataBuf])))
  return Buffer.concat([lenBuf, typeBuf, dataBuf, crcBuf])
}

function buildPng(chunks: { type: string, data: string }[]): Buffer {
  return Buffer.concat([PNG_SIGNATURE, ...chunks.map(c => pngChunk(c.type, c.data)), pngChunk('IEND', '')])
}

function jpegApp1(payload: string): Buffer {
  const data = Buffer.from(payload, 'latin1')
  const marker = Buffer.from([0xff, 0xe1])
  const len = Buffer.alloc(2); len.writeUInt16BE(data.length + 2)
  return Buffer.concat([marker, len, data])
}

function buildJpeg(app1Payloads: string[]): Buffer {
  const soi = Buffer.from([0xff, 0xd8])
  const sos = Buffer.from([0xff, 0xda, 0x00, 0x02]) // SOS minimale: da qui in poi solo dati grezzi
  const scan = Buffer.from([0x00, 0x01, 0x02])
  const eoi = Buffer.from([0xff, 0xd9])
  return Buffer.concat([soi, ...app1Payloads.map(jpegApp1), sos, scan, eoi])
}

describe('imageMetadata: detectImageFormat', () => {
  it('recognizes PNG and JPEG signatures, rejects anything else', () => {
    expect(detectImageFormat(buildPng([]))).toBe('png')
    expect(detectImageFormat(buildJpeg([]))).toBe('jpeg')
    expect(detectImageFormat(Buffer.from('not an image'))).toBe(null)
  })
})

describe('imageMetadata: PNG stripping', () => {
  it('mode "all" removes every tEXt/iTXt/eXIf/tIME chunk, keeps IHDR/IDAT', () => {
    const buf = buildPng([
      { type: 'IHDR', data: 'header' },
      { type: 'tEXt', data: 'Software: Midjourney' },
      { type: 'tEXt', data: 'Author: Giuseppe' },
      { type: 'IDAT', data: 'pixel data' }
    ])
    const { output, removedChunks } = stripImageMetadata(buf, 'all')
    expect(removedChunks).toEqual(['tEXt', 'tEXt'])
    const text = output.toString('latin1')
    expect(text).not.toContain('Midjourney')
    expect(text).not.toContain('Giuseppe')
    expect(text).toContain('pixel data') // IDAT intatto
  })

  it('mode "ai-only" removes only chunks matching a known AI-tool signature', () => {
    const buf = buildPng([
      { type: 'IHDR', data: 'header' },
      { type: 'tEXt', data: 'Software: Midjourney' },
      { type: 'tEXt', data: 'Author: Giuseppe' },
      { type: 'IDAT', data: 'pixel data' }
    ])
    const { output, removedChunks } = stripImageMetadata(buf, 'ai-only')
    expect(removedChunks).toEqual(['tEXt'])
    const text = output.toString('latin1')
    expect(text).not.toContain('Midjourney')
    expect(text).toContain('Giuseppe') // metadato non-AI: deve sopravvivere
  })

  it('reports zero removed chunks (not an error) when the file has no text metadata', () => {
    const buf = buildPng([{ type: 'IHDR', data: 'header' }, { type: 'IDAT', data: 'pixels' }])
    const { removedChunks, output } = stripImageMetadata(buf, 'all')
    expect(removedChunks).toEqual([])
    expect(output.equals(buf)).toBe(true)
  })

  it('never touches IHDR/IDAT/IEND bytes even when stripping around them', () => {
    const buf = buildPng([
      { type: 'IHDR', data: 'header-bytes' },
      { type: 'tEXt', data: 'Generated by DALL-E' },
      { type: 'IDAT', data: 'exact-pixel-bytes' }
    ])
    const { output } = stripImageMetadata(buf, 'all')
    const text = output.toString('latin1')
    expect(text).toContain('header-bytes')
    expect(text).toContain('exact-pixel-bytes')
  })
})

describe('imageMetadata: JPEG stripping', () => {
  it('mode "all" removes APP1 (EXIF/XMP) segments, keeps the scan data', () => {
    const buf = buildJpeg(['Exif\0\0Software: Stable Diffusion'])
    const { output, removedChunks, format } = stripImageMetadata(buf, 'all')
    expect(format).toBe('jpeg')
    expect(removedChunks.length).toBe(1)
    const text = output.toString('latin1')
    expect(text).not.toContain('Stable Diffusion')
    // SOI/EOI e i byte di scan restano al loro posto
    expect(output[0]).toBe(0xff)
    expect(output[1]).toBe(0xd8)
    expect(output[output.length - 2]).toBe(0xff)
    expect(output[output.length - 1]).toBe(0xd9)
  })

  it('mode "ai-only" leaves an APP1 segment alone when it matches no known AI signature', () => {
    const buf = buildJpeg(['Exif\0\0Make: Canon, Model: EOS R5'])
    const { output, removedChunks } = stripImageMetadata(buf, 'ai-only')
    expect(removedChunks).toEqual([])
    expect(output.toString('latin1')).toContain('Canon')
  })

  it('rejects a buffer without a valid JPEG/PNG signature', () => {
    expect(() => stripImageMetadata(Buffer.from('garbage'))).toThrow()
  })
})
